[package]
name = "app"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
gpui.workspace = true
gpui-platform.workspace = true
anyhow.workspace = true
zalmoxis.workspace = true
danubius.workspace = true
components = { path = "../components" }
dsp = { path = "../dsp" }
split = { path = "../split" }
tokio.workspace = true

[lints.clippy]
all = "warn"
