[package]
name = "audio"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde.workspace = true
thiserror.workspace = true
coreaudio-rs.workspace = true
coreaudio-sys.workspace = true

[lints.clippy]
all = "warn"