[package]
name = "dsp"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
gpui.workspace = true
zalmoxis.workspace = true
components = { path = "../components" }
design_pattern =  { path = "../design_pattern/"} 
danubius.workspace = true
[lints.clippy]
all = "warn"
