#!/usr/bin/env bash
set -euo pipefail

current_branch=$(git rev-parse --abbrev-ref HEAD)
if [ "$current_branch" != "master" ]; then
  exit 0
fi

cargo fmt
git update-index --again
cargo clippy --workspace -- -D warnings
